project_name: azion

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/azion
    ldflags:
      - -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion={{ .Env.BIN_VERSION }}
      - -X github.com/aziontech/azion-cli/pkg/constants.AuthURL={{ .Env.AUTH_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.ApiURL={{ .Env.API_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL={{ .Env.STORAGE_URL }}
      - -X github.com/aziontech/azion-cli/pkg/pkg/cmd/edge_applications/init.TemplateBranch={{ .Env.TEMPLATE_BRANCH }}
    binary: azion
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - files:
      - completions/*

before:
  hooks:
    - chmod +x ./scripts/completions.sh
    - ./scripts/completions.sh

brews:
  - name: azion
    homepage: https://github.com/aziontech/azion-cli
    description: The developer friendly way to interact with Azion
    license: "MIT"
    dependencies:
      - name: jq
    tap:
      owner: aziontech
      name: homebrew-tap
    install: |
      bin.install "azion"
      bash_completion.install "completions/azion.bash" => "azion"
      zsh_completion.install "completions/azion.zsh" => "_azion"
      fish_completion.install "completions/azion.fish"      

nfpms:
  - id: packages
    license: MIT
    package_name: azion
    maintainer: aziontech
    homepage: https://github.com/aziontech/azion-cli
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
  - contents:
    - src: completions/azion.bash
      dst: /usr/share/bash-completion/completions/azion
      file_info:
        mode: 0644
    - src: completions/azion.fish
      dst: /usr/share/fish/vendor_completions.d/azion.fish
      file_info:
        mode: 0644
    - src: completions/azion.zsh
      dst: /usr/share/zsh/vendor-completions/_azion
      file_info:
        mode: 0644

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.BIN_VERSION }}_checksum"
snapshot:
  name_template: "{{ incpatch .Env.BIN_VERSION }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Breaking Changes"
      regexp: "^.*breaking[(\\w)]*:+.*$"
      order: 0
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: 'Improvements'
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 20
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 30
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 40
    - title: 'Documentation Updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 50
    - title: Other Work
      order: 999
