project_name: azion

builds:
  - env:
    id: azion-unix
      - CGO_ENABLED=0
    main: ./cmd/azion
    ldflags:
      - -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion={{ .Env.BIN_VERSION }}
      - -X github.com/aziontech/azion-cli/pkg/metric/metric.SegmentKey={{ .Env.SEGMENT_KEY }}
      - -X github.com/aziontech/azion-cli/pkg/constants.AuthURL={{ .Env.AUTH_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.ApiURL={{ .Env.API_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL={{ .Env.STORAGE_URL }}
      - -X github.com/aziontech/azion-cli/pkg/pkg/cmd/edge_applications/init.TemplateBranch={{ .Env.TEMPLATE_BRANCH }}
    binary: azion
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm

  - env:
    id: azion-windows
      - CGO_ENABLED=0
    main: ./cmd/azion
    ldflags:
      - -X github.com/aziontech/azion-cli/pkg/cmd/version.BinVersion={{ .Env.BIN_VERSION }}
      - -X github.com/aziontech/azion-cli/pkg/metric/metric.SegmentKey={{ .Env.SEGMENT_KEY }}
      - -X github.com/aziontech/azion-cli/pkg/constants.AuthURL={{ .Env.AUTH_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.ApiURL={{ .Env.API_URL }}
      - -X github.com/aziontech/azion-cli/pkg/constants.StorageApiURL={{ .Env.STORAGE_URL }}
      - -X github.com/aziontech/azion-cli/pkg/pkg/cmd/edge_applications/init.TemplateBranch={{ .Env.TEMPLATE_BRANCH }}
    binary: azion
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

archives:
  # Non-Windows platforms (Linux, macOS, etc.)
  - id: non-windows
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Tag }}"
    format: tar.gz
    files:
      - completions/*
      - ./dist/azion-{{ .Os }}_{{ .Arch }}/azion

  # Windows platforms
  - id: windows
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Tag }}.zip"
    format: zip
    files:
      - ./dist/azion-windows - CGO_ENABLED=0_windows_386_sse2/azion.exe    # 32-bit Windows (386)
      - ./dist/azion-windows - CGO_ENABLED=0_windows_amd64_v1/azion.exe    # 64-bit Windows (amd64)
      - ./dist/azion-windows - CGO_ENABLED=0_windows_arm64_v8.0/azion.exe  # ARM64 Windows


before:
  hooks:
    - chmod +x ./scripts/completions.sh
    - ./scripts/completions.sh

nfpms:
  - id: packages
    license: MIT
    maintainer: Azion Technologies <https://github.com/aziontech>
    package_name: azion
    homepage: https://github.com/aziontech/azion
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
  - contents:
      - src: completions/azion.bash
        dst: /usr/share/bash-completion/completions/azion
        file_info:
          mode: 0644
      - src: completions/azion.fish
        dst: /usr/share/fish/vendor_completions.d/azion.fish
        file_info:
          mode: 0644
      - src: completions/azion.zsh
        dst: /usr/share/zsh/vendor-completions/_azion
        file_info:
          mode: 0644

chocolateys:
  - name: azion

    package_source_url: https://github.com/aziontech/azion/releases

    owners: aziontech

    title: azion

    authors: PatrickMenoti

    project_url: https://github.com/aziontech/azion

    url_template: "http://downloads.azion.com/windows/x86_64/azion"

    license_url: https://github.com/aziontech/azion/blob/dev/LICENSE

    require_license_acceptance: false

    project_source_url: https://github.com/aziontech/azion

    docs_url: https://www.azion.com/en/documentation/products/azion-cli/overview

    bug_tracker_url: https://github.com/aziontech/azion/issues

    tags: "azion cli go publish deploy build jamstack"

    summary: Use Azion CLI for managing Azion services via command-line.

    description: Azion CLI is a user-friendly way to work with the Azion Edge Platform, allowing you to create and manage applications through simple commands.

    release_notes: "https://github.com/aziontech/azion/releases/tag/{{ .Version }}"

    api_key: "{{ .Env.CHOCOLATEY_TOKEN }}"

    source_repo: "https://push.chocolatey.org/"

    goamd64: v1

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.BIN_VERSION }}_checksum"
snapshot:
  name_template: "{{ incpatch .Env.BIN_VERSION }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Breaking Changes"
      regexp: "^.*breaking[(\\w)]*:+.*$"
      order: 0
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Improvements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 20
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 30
    - title: "Security Updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 40
    - title: "Documentation Updates"
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 50
    - title: "Tests"
      regexp: ^.*?(test(s)?(\([[:word:]]+\))?)!?:.+$
      order: 60
    - title: Other Work
      order: 999
