name: CI - Security

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '40 3 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aziontech/azion-action-security@v0
