name: "CLA Assistant"
on:
  push:
    branches:
      - '**'

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    container:
      image: maxwelbm/cla:test

    steps:
      - name: "CLA Assistant"
        # if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/aziontech/azion/blob/main/CLA.md'
          branch: 'main'
          allowlist: user1,bot*
          remote-organization-name: 'aziontech'
          remote-repository-name: 'cla' 
