name: Package Auditing

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  PackageAuditing:
    permissions:
      contents: write
      pull-requests: write
    name: Package Auditor (GoVulnCheck)
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-vulncheck') }}
    container:
      image: golang:1.25.13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      
      - name: bypass dep
        run: go env -w GOPRIVATE=github.com/zRedShift/mimemagic

      - name: Download dependencies
        run: go mod download

      - name: GoVulnCheck
        run: make govulncheck
