name: Test and Build

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches-ignore:
      - main 

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-unit-tests') }}
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.13

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setting up a secure repository
        run: git config --global --add safe.directory /__w/azion/azion

      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        name: run goreleaser check
        with:
          distribution: goreleaser
          version: 2.3.2
          args: check

      - name: Build & Test (skip v3 tests)
        run: |
          echo "Building and testing (skipping v3 tests)"
          mkdir -p cover
          PKGS=$(go list ./... | grep -v "/pkg/v3commands/")
          echo "Testing packages:" $PKGS
          go test -v -failfast -coverprofile ./cover/azioncoverage.out -coverpkg=$(echo "$PKGS" | tr '\n' ',') $PKGS
          go tool cover -html=./cover/azioncoverage.out -o ./cover/azioncoverage.html
          go tool cover -func ./cover/azioncoverage.out
          make build

      - name: Gosec
        run: |
          echo "Checking Security"
          make sec

      - name: Go Report
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0
